spring:
  application:
    name: ${APP_NAME:MyApplication}
  datasource:
    url: jdbc:mysql://10.252.1.0:3306/EmployeeManagement?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
server:
  servlet:
    context-path: /api